# Generated by Django 2.1.1 on 2018-09-09 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topics',
            options={'verbose_name': 'topics', 'verbose_name_plural': 'topics'},
        ),
    ]
