# Generated by Django 2.1.1 on 2018-09-09 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_auto_20180909_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
