# Generated by Django 2.1.1 on 2018-09-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_topics_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='comment',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
