# Generated by Django 2.1.1 on 2018-09-09 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0008_entry'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='entry',
            table='entry',
        ),
        migrations.AlterModelTable(
            name='topics',
            table='topics',
        ),
    ]
