# Generated by Django 2.1.1 on 2018-09-10 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0009_auto_20180909_2034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='topics',
            new_name='Topic',
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'topic', 'verbose_name_plural': 'topics'},
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic',
            new_name='text',
        ),
    ]
