# Generated by Django 2.1.1 on 2018-09-18 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0011_topic_ower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='ower',
            new_name='owner',
        ),
    ]
